spring:
  cloud:
    gateway:
      routes:

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api(?<segment>.*),$\{segment}

        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api(?<segment>.*),$\{segment}

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api(?<segment>.*),$\{segment}

        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty(?<segment>.*),$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>.*),/renren-fast$\{segment}

        - id: coemall_host_route
          uri: lb://mall-product
          predicates:
            - Host=coemall.com,item.coemall.com

        - id: coemall_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.coemall.com

        - id: mall_auth_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.coemall.com

        - id: mall_cart_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.coemall.com
