server:
  port: 11000
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.80.133:3306/mall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    com.learn.coemall: debug