server:
  port: 10000
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
#      逻辑删除：
#        1.配置全局的逻辑删除规则（可省略）
#        2.配置逻辑删除的组件Bean（3.1.0后可省略）
#        3.加上逻辑删除注解@TableLogic
spring:

  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.80.133:3306/mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: mall-product

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false

  redis:
    host: 192.168.80.133

  cache:
    type: redis
    redis:
      time-to-live: 3600000
#      key-prefix: CACHE_
      use-key-prefix: true
      cache-null-values: true #是否缓存控制，防止缓存穿透

logging:
  level:
    com.learn.coemall: debug