server:
  port: 16000
spring:
  application:
    name: mall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.80.133
  rabbitmq:
    virtual-host: /
    host: 192.168.80.133