server:
  port: 14000
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.80.133
    port: 6379
  session:
    store-type: redis
