spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tLgAz2AYgcFsPPWVCG7
      secret-key: XelHrm0Ph4iNtLcCXOxtk7GvFY6tYR
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: coemall
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        sign: 2e65b1bb3d054466b82f0c9d125465e2
        template: 908e94ccf08b4476ba6c876d13f084ad
        appCode: ed787bd4eb3749b9bef193a9c2259fe8
  application:
    name: mall-third-party
server:
  port: 12000